apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefoods-backend
  labels:
    app: kubefoods
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubefoods
  template:
    metadata:
      labels:
        app: kubefoods
    spec:
      containers:
      - name: nginx
        image: julimega/kubefoods-backend:latest  # ‚Üê IMAGEN CORRECTA
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health.html
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5