name: CI/CD KubeFoods

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login Docker Hub
      run: echo "${{ secrets.Prueba1234 }}" | docker login -u "${{ secrets.julimega }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.julimega }}/kubefoods-backend:latest .

    - name: Push image
      run: docker push ${{ secrets.julimega }}/kubefoods-backend:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Apply manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Validate deployment
      run: bash scripts/validate.sh
