name: CI/CD KubeFoods

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/kubefoods-backend:latest .

    - name: Push image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/kubefoods-backend:latest

    # --- CREAR CLUSTER KUBERNETES ----
    - name: Install kind
      uses: helm/kind-action@v1.8.0

    - name: Check cluster
      run: kubectl get nodes

    # --- DESPLIEGUE ----
    - name: Apply manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    # --- VALIDACIÃ“N ----
    - name: Validate deployment
      run: bash scripts/validate.sh
